### ISSUE TITLE
Scrollbar style is not matched with theme in chrome

### ISSUE THREAD

**Issue by gwanryo** [gwanryo/ohmycodes#6]
![image](https://user-images.githubusercontent.com/9062624/167297644-2c09cec2-939a-491a-9dd5-e2b85422440e.png)

**Comment by gwanryo** [comment]
It occurs in Windows, Chrome

**Comment by blurfx** [comment]
라식하셈

**Comment by gwanryo** [comment]
It seems default value of `scrollbarStyle` is `native`, so it occurs only in Windows.

**Comment by fienestar** [comment]
Sample scrollbar style works in windows
```css
*::-webkit-scrollbar {
    background: rgba(0,0,0,0);
    max-width: 0.5rem;
}

*::-webkit-scrollbar-thumb {
    background-color: black;
    border-radius: 1rem;
}

*::-webkit-scrollbar-corner {
    background: rgba(0,0,0,0);
}
```

**Comment by gwanryo** [comment]
Thanks @fienestar , I just added additional lines based on your code.

```css
*::-webkit-scrollbar {
    background: rgba(0, 0, 0, 0);
    max-width: 0.5rem;
    max-height: 0.5rem;
}

*::-webkit-scrollbar-thumb {
    background-color: rgba(255, 255, 255, 0.25);
    border-radius: 0.5rem;
}

*::-webkit-scrollbar-corner {
    background: rgba(0, 0, 0, 0);
}

.CodeMirror-scrollbar-filler, .CodeMirror-gutter-filler {
    background: rgba(0, 0, 0, 0) !important;
}
```
